### ISSUE TITLE
[KVNProgress showProgress: status:  onView: ] (on view not working?)

### ISSUE THREAD

**Issue by JustinDMoore** [kevin-hirsch/KVNProgress#12] opened 2014-12-22 04:05 UTC
I just updated from 2.1.3 to 2.1.5 today, and now have this issue. Please see attached screenshot.

In my custom view xib .m, I am calling showProgress: status: onView:, but KVNProgress always centers itself vertically and horizontally on the main view. In my xib, I have a UIView that I set the frame to 50x50 and set ClipsSubviews = YES. The KVNProgress view positions itself outside of the UIView, and is not clipped. Here is the complete code. Please let me know if I can provide any more information.

As a side note, why do all the views 'behind' the KVNProgress become dimmed? Can I prevent that that?

Thanks, love this.

   ```objc
    -(id)initWithCoder:(NSCoder *)aDecoder {
        
        self = [super initWithCoder:aDecoder];
        if (self) {
            self.clipsToBounds = YES;
            self.backgroundColor = [UIColor orangeColor]; //for debugging the frame
            self.customConfiguration = [self customKVNProgressUIConfiguration];
            [KVNProgress setConfiguration:self.customConfiguration];
            [self progress];

        }
        return self;
    }

    - (KVNProgressConfiguration *)customKVNProgressUIConfiguration
    {
        KVNProgressConfiguration *configuration = [[KVNProgressConfiguration alloc] init];

        configuration.statusColor = [UIColor whiteColor];
        configuration.statusFont = [UIFont fontWithName:@"HelveticaNeue-Thin" size:15.0f];
        configuration.circleStrokeForegroundColor = [UIColor colorWithRed:0/255.0 green:174/255.0 blue:237/255.0 alpha:1];
        configuration.circleStrokeBackgroundColor = [[UIColor darkGrayColor] colorWithAlphaComponent:0.3f];
        configuration.circleFillBackgroundColor = [UIColor clearColor];
        configuration.backgroundFillColor = [UIColor yellowColor]; // for debugging the frame
        configuration.backgroundTintColor = [UIColor redColor]; // for debugging the frame
        configuration.successColor = [UIColor greenColor];
        configuration.errorColor = [UIColor redColor];
        configuration.circleSize = 75.0f;
        configuration.lineWidth = 2.0f;
        configuration.backgroundType = KVNProgressBackgroundTypeSolid;
        configuration.fullScreen = NO;

        return configuration;
    }

    -(void)progress {
        
        //[KVNProgress showProgress:0];
        [KVNProgress showProgress:0
                           status:nil
                           onView:self.viewProgress];
        [self updateProgress];

    }

    - (void)updateProgress
    {
        dispatch_time_t popTime1 = dispatch_time(DISPATCH_TIME_NOW, 1.0f * NSEC_PER_SEC);
        dispatch_after(popTime1, dispatch_get_main_queue(), ^(void){
            [self updateWithProgress:[self getRandomProgressWithMin]];
        });
        
        dispatch_time_t popTime2 = dispatch_time(DISPATCH_TIME_NOW, 2.0f * NSEC_PER_SEC);
        dispatch_after(popTime2, dispatch_get_main_queue(), ^(void){
            [self updateWithProgress:[self getRandomProgressWithMin]];
        });
        
        dispatch_time_t popTime4 = dispatch_time(DISPATCH_TIME_NOW, 3.0f * NSEC_PER_SEC);
        dispatch_after(popTime4, dispatch_get_main_queue(), ^(void){
            [self updateWithProgress:[self getRandomProgressWithMin]];
        });
        
    }

    -(void)updateWithProgress:(double)progress {
        
        if (!isComplete) {
            [KVNProgress updateProgress:progress
                               animated:YES];
        }
    }
   ```

![screenshot at dec 21 19-56-01](https://cloud.githubusercontent.com/assets/8095607/5521118/0b40e400-894c-11e4-8829-301b166ce96b.png)

**Comment by kevin-hirsch** [comment] 2015-01-11 12:31
I will check this issue today. I'll also add in a second time a BOOL to enable/disable user interaction while the HUD is displayed ;)

**Comment by kevin-hirsch** [comment] 2015-01-11 13:34
@JustinDMoore, do you have any constraints error logged in your console while showing the HUD?

**Comment by kevin-hirsch** [comment] 2015-01-11 19:43
@JustinDMoore, I was unable to reproduce your issue. Here is what I did:

1. I created a `UIViewController` with this code:

   ```objc
   - (void)viewDidLoad {
       [super viewDidLoad];
   	
	   KVNSmallView *view = [[UINib nibWithNibName:@"KVNSmallView"
	   								        bundle:nil]
	   					  instantiateWithOwner:self
	   					  options:nil][0];
	
	   [self.view addSubview:view];
	
	   view.translatesAutoresizingMaskIntoConstraints = NO;
	   [self.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[view]|"
   																	     options:0
   																	     metrics:nil
																		   views:NSDictionaryOfVariableBindings(view)]];
   	   [self.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:[view(284)]|"
   																	     options:0
   																	     metrics:nil
   																		   views:NSDictionaryOfVariableBindings(view)]];
   }
   ```

2. The `KVNSmallView` class:

   ```objc
@interface KVNSmallView ()

@property (nonatomic, weak) IBOutlet UIView *progressView;

@property (nonatomic) KVNProgressConfiguration *customConfiguration;

@end

@implementation KVNSmallView

-(id)initWithCoder:(NSCoder *)aDecoder
{
	   self = [super initWithCoder:aDecoder];
	   if (self) {
	   	self.clipsToBounds = YES;
	   	self.backgroundColor = [UIColor orangeColor]; //for debugging the frame
	   	self.customConfiguration = [self customKVNProgressUIConfiguration];
	   	[KVNProgress setConfiguration:self.customConfiguration];
	   }
	   return self;
}

- (void)awakeFromNib
{
         [self progress];
}

- (KVNProgressConfiguration *)customKVNProgressUIConfiguration
{
	   KVNProgressConfiguration *configuration = [[KVNProgressConfiguration alloc] init];
	
	   configuration.statusColor = [UIColor whiteColor];
	   configuration.statusFont = [UIFont fontWithName:@"HelveticaNeue-Thin" size:15.0f];
	   configuration.circleStrokeForegroundColor = [UIColor colorWithRed:0/255.0 green:174/255.0 blue:237/255.0 alpha:1];
	   configuration.circleStrokeBackgroundColor = [[UIColor darkGrayColor] colorWithAlphaComponent:0.3f];
	   configuration.circleFillBackgroundColor = [UIColor clearColor];
	   configuration.backgroundFillColor = [UIColor yellowColor]; // for debugging the frame
	   configuration.backgroundTintColor = [UIColor redColor]; // for debugging the frame
	   configuration.successColor = [UIColor greenColor];
	   configuration.errorColor = [UIColor redColor];
	   configuration.circleSize = 75.0f;
	   configuration.lineWidth = 2.0f;
	   configuration.backgroundType = KVNProgressBackgroundTypeSolid;
	   configuration.fullScreen = NO;
	
	   return configuration;
}

- (void)progress
{
	   [KVNProgress showWithStatus:nil
						    onView:self.progressView];
	
}

@end
   ```

3. Here is the xib of this `KVNSmallView`:

![kvnsmallview](https://cloud.githubusercontent.com/assets/2794684/5696454/65efdd84-99d2-11e4-988e-2ad7257f9225.png)

4. And that is the result I have:

![result](https://cloud.githubusercontent.com/assets/2794684/5696455/6fccab48-99d2-11e4-87c5-21db48f6ea16.png)

All seems to work fine.
I'm using the version 2.1.6 but I don't think it changes something for this issue between 2.1.5 and 2.1.6.
All I changed from your example is the call of the method `progress` that I put in the `awakeFromNib` method, because otherwise the `progressView` property will be nil before that point.

I think that calling the HUD from the `initWithCoder` method is too soon.
Can you try to fix this for you and tell me if it works? :)
Or tell me if I'm doing something different than you in my test.

Hope it helps! ;)

**Comment by JustinDMoore** [comment] 2015-01-11 21:34
Thanks for working on this. I'll be back in my office later tonight and I'll see what I can come up with.

**Comment by JustinDMoore** [comment] 2015-01-13 07:26
Sorry for the delay. I moved [self progress] to -awakeFromNib and it looks like it's supposed to now.

**Comment by kevin-hirsch** [comment] 2015-01-13 10:00
Great! :)
I'm closing this issue ;)

**Closed by kevin-hirsch** 2015-01-13 10:00 UTC
Labels: bug
